### ISSUE TITLE
Libraries location

### ISSUE THREAD

**Issue by pedro-dreyer** [jpuigcerver/rnn2d#4]
In the installation instruction there is the following line:

Once you have installed the library, do not forget to update the LD_LIBRARY_PATH environment variable appropriately, so that Lua FFI can load the required dynamic libraries.

Where exactly are the libraries located?

**Comment by jpuigcerver** [comment]
Did you installed the library using luarocks? If that is the case, they should be in $TORCH_ROOT/install/lib/lua/5.1/librnn2d_{cpu,gpu}.so. Typically TORCH_ROOT is $HOME/torch, but it depends on your particular configuration.

For instance, in my computer I have the following lines in my `.bashrc` file.
```bash
source /opt/torch/install/bin/torch-activate
export RNN2D_LIBCPU_PATH=/opt/torch/install/lib/lua/5.1/librnn2d_cpu.so
export RNN2D_LIBGPU_PATH=/opt/torch/install/lib/lua/5.1/librnn2d_gpu.so
```
